---
class_path: superhuge.data.interface.DInterface
init_args:
  dataloader_args:
    batch_size: 64
    drop_last: false
    num_workers: 4
    persistent_workers: true
    pin_memory: true
    prefetch_factor: 8
  dataset_class: superhuge.data.datasets.EegDataset
  fs: 128
  meta_filter_func:
    - class_path: superhuge.data.metadata_filters.MetadataValueSelector
      init_args:
        attribute_name: dataset_id
        attribute_value:
          # - 1 # AHU
          # - 2 # DTU
          # - 3 # Estart
          - 4 # KUL: lrtc?
          # - 5 # KUL-AV-GC?
          # - 6 # NJU
          # - 7 # NUS
          # - 8 # PKU?
          # - 9 # PKU-NBD
          # - 10 # sparKULee
  overlap: 1
  # root_path: /home/sean/data/SuperHuge
  root_path: /mnt/e/derivatives/SuperHuge
  preproc_stage: preprocessed
  transform:
    null
    # - class_path: superhuge.data.transforms.Scale
    #   init_args:
    #     preproc_stage: ${init_args.preproc_stage}
    #     apply_prob: 1.0
    #     when: before_returning
    #     whom: [eeg, env]
    #     root_path: ${init_args.root_path}
    #     scaling_factor_path: scaling_factor.pkl
    # - class_path: superhuge.data.transforms.ZScore
    #   init_args:
    #     apply_prob: 1.0
    #     when: before_returning
    #     whom: audio
  window_length: 10
  summary_verbose: true
